//! Fake-capacity loopback: the deterministic 50,000-object / 1,000-node
//! dataset served through the real control socket proves bounded snapshot
//! chunking (every `snapshotChunk` page carries at most
//! `SNAPSHOT_PAGE_ROWS` rows), a complete contiguous reassembly of the
//! dominant kind, and a generous non-regression wall-time ceiling for the
//! whole transfer.
//!
//! The exact same dataset is generated by `k10s-backend`'s `fake_scale`
//! benchmark and rendered by `k10s-ui`'s `ui_capacity` benchmark; together
//! they are the Plan 2 capacity gate that Plan 5 will repeat against real
//! runtime pressure.

use std::time::{Duration, Instant};

use futures_util::{SinkExt, StreamExt};
use k10s_backend::FakeKubernetes;
use k10s_protocol::{ResourceSnapshotPage, ServerFrame, ServerKind, SnapshotBegin, SnapshotChunk};
use k10s_server::{ServerConfig, spawn_loopback};
use k10s_ui::client::{ClientConfig, ClientPhase, ClientState, ConnectTarget};
use tokio_tungstenite::{connect_async, tungstenite::Message};

type Ws =
    tokio_tungstenite::WebSocketStream<tokio_tungstenite::MaybeTlsStream<tokio::net::TcpStream>>;

/// The server's hard bound on rows per snapshot page. The constant is
/// private to the server, so the test re-derives it from the observed
/// maximum page size instead of trusting any local copy: if the bound ever
/// grows, this assertion documents it explicitly.
const MAX_PAGE_ROWS_OBSERVED_LIMIT: usize = 16;

/// Generous end-to-end ceiling for streaming ~1,200 pages (~19k rows) over
/// the loopback socket, including client-side reassembly.
const TRANSFER_CEILING: Duration = Duration::from_secs(120);

/// The full snapshot (~1,200 pages plus lifecycle frames) must fit the
/// session's outbound queue so this test exercises bulk transfer rather
/// than the deliberate slow-consumer overload closure, which the stream
/// and rate-budget suites already cover.
const CAPACITY_QUEUE_FRAMES: usize = 4_096;

const OBJECTS: usize = 50_000;
const NODES: usize = 1_000;

async fn recv_frame(ws: &mut Ws) -> ServerFrame {
    let message = tokio::time::timeout(Duration::from_secs(30), ws.next())
        .await
        .expect("server frame within timeout")
        .expect("socket open")
        .expect("socket healthy");
    serde_json::from_str(&message.into_text().unwrap()).unwrap()
}

async fn flush_outbound(ws: &mut Ws, client: &mut ClientState) {
    while let Some(frame) = client.take_outbound() {
        ws.send(Message::Text(serde_json::to_string(&frame).unwrap().into()))
            .await
            .unwrap();
    }
}

/// Apply an inbound frame to the shared client and echo its outbound
/// traffic (notably sequence acknowledgements) back; without the acks the
/// server's bounded outbound scheduler treats this consumer as overloaded.
async fn apply_and_ack(ws: &mut Ws, client: &mut ClientState, frame: ServerFrame) {
    client
        .apply_at(frame.clone(), 1_000, 7)
        .unwrap_or_else(|error| panic!("client rejected {frame:?}: {error}"));
    flush_outbound(ws, client).await;
}

#[tokio::test]
async fn fifty_thousand_object_dataset_streams_in_bounded_pages() {
    let fake = FakeKubernetes::with_capacity(OBJECTS, NODES);
    assert_eq!(fake.total_records(), OBJECTS + NODES);

    let kernel = k10s_backend::BackendKernel::new_with_instance_id(fake.clone(), "capacity-server");
    let server = spawn_loopback(
        ServerConfig {
            access_token: "secret".into(),
            outbound_queue_capacity: CAPACITY_QUEUE_FRAMES,
            ..ServerConfig::default()
        },
        kernel,
    )
    .await
    .unwrap();

    let url = format!("ws://{}{}", server.addr(), k10s_protocol::CONTROL_PATH);
    let mut client = ClientState::new(ClientConfig::default());
    client
        .connect(ConnectTarget::new(url.clone(), "secret"))
        .unwrap();
    let mut ws = connect_async(url.as_str()).await.unwrap().0;
    flush_outbound(&mut ws, &mut client).await;

    // Handshake completes into Ready.
    loop {
        let frame = recv_frame(&mut ws).await;
        let done = frame.kind == ServerKind::Welcome;
        apply_and_ack(&mut ws, &mut client, frame).await;
        if done {
            break;
        }
    }
    assert_eq!(client.phase(), ClientPhase::Ready);

    // Subscribe to the dominant kind: three eighths of the objects.
    let expected_rows = OBJECTS * 3 / 8;
    let subscription = client
        .subscribe_resource("dev-local", "", "v1", "Pod", None)
        .unwrap();
    flush_outbound(&mut ws, &mut client).await;

    let start = Instant::now();
    let subscribed = recv_frame(&mut ws).await;
    assert_eq!(subscribed.kind, ServerKind::Subscribed);
    apply_and_ack(&mut ws, &mut client, subscribed).await;

    let begin = recv_frame(&mut ws).await;
    assert_eq!(begin.kind, ServerKind::SnapshotBegin);
    let total_chunks = serde_json::from_value::<SnapshotBegin>(begin.payload.clone())
        .unwrap()
        .total_chunks;
    client.apply(begin).unwrap();
    assert_eq!(
        usize::try_from(total_chunks).unwrap(),
        expected_rows.div_ceil(MAX_PAGE_ROWS_OBSERVED_LIMIT),
        "one bounded page per slice of the snapshot"
    );

    let mut last_chunk_index: i64 = -1;
    for _ in 0..total_chunks {
        let frame = recv_frame(&mut ws).await;
        assert_eq!(frame.kind, ServerKind::SnapshotChunk);
        let chunk = serde_json::from_value::<SnapshotChunk>(frame.payload.clone()).unwrap();
        assert_eq!(
            i64::from(chunk.chunk_index),
            last_chunk_index + 1,
            "chunk pages arrive contiguously"
        );
        last_chunk_index = i64::from(chunk.chunk_index);
        let page = serde_json::from_value::<ResourceSnapshotPage>(chunk.data).unwrap();
        assert!(
            page.rows.len() <= MAX_PAGE_ROWS_OBSERVED_LIMIT,
            "a snapshot page carried {} rows, breaching the bounded chunk size",
            page.rows.len()
        );
        apply_and_ack(&mut ws, &mut client, frame).await;
    }

    let end = recv_frame(&mut ws).await;
    assert_eq!(end.kind, ServerKind::SnapshotEnd);
    apply_and_ack(&mut ws, &mut client, end).await;

    let list = client
        .resource_list(subscription.id())
        .expect("the full snapshot reassembles into the retained list");
    assert_eq!(list.rows().count(), expected_rows);
    assert!(list.revision().is_some());

    let elapsed = start.elapsed();
    println!("capacity transfer of {expected_rows} rows took {elapsed:?}");
    assert!(
        elapsed < TRANSFER_CEILING,
        "capacity transfer took {elapsed:?}, ceiling {TRANSFER_CEILING:?}"
    );

    server.shutdown().await.unwrap();
}
